Simplify build process
elementary/appcenter-web pull request #34
Opened 2019-02-14 05:20 UTC by RMcNeely

#### Overview:
Creates a small Ruby program that reads a Yaml file of release info to generate markdown pages of new release info. These new changes are outlines briefly in the README file.

Ruby program reads releases.yaml file to gather info on server, and for each release generates a new yaml file (so that the MD templates can be generated independently of querying the server again). The program then iterates thru the new yaml files for each release (located in `_data/`) to create a markdown file for each app. 

#### Technial Changes:
- New singular build command `bin/run.rb`
- Two distinct ruby programs each with its own task which can be run independently
  - `fetch_packages.rb` run this file to query the server and download the newest release data
  - `generate_listings.rb` run this to read the data returned from the server to generate MD files for each app
    -`app_template.rb` provides an ERB template for generating the markdown per app
- `releases.yaml` file allows for easily updating. (presuming no server changes for new releases).

2019-02-14 19:22 UTC, cassidyjames commented
Note to reviewers: don't be too daunted by the massive diff! :sweat_smile: This PR includes updated yaml and md files for the apps.

2019-02-14 19:41 UTC, cassidyjames commented
@RMcNeely it looks like some screenshots and icons aren't loading on your branch, but load on master just fine. Are you able to reproduce that on your end?

2019-02-14 19:41 UTC, RMcNeely commented
Haha I tried to keep the diff something managable so it was easier to review. If you run the new build process it will produce changes in the MD files themselves but its only adding quotes around strings in the header and some white space changes. Its a little scary to look at the diff but visually when you run Jekyll its the same

2019-02-14 19:42 UTC, RMcNeely commented
> @RMcNeely it looks like some screenshots and icons aren't loading on your branch, but load on master just fine. Are you able to reproduce that on your end?

I

2019-02-14 19:55 UTC, RMcNeely commented
> @RMcNeely it looks like some icons (Desktop Folder, Eddy, Gifup, Harvey, Memories, Metronome, Screencast, Taxi, News) and some screenshots aren't loading on your branch, but load on master just fine. Are you able to reproduce that on your end?

It looks like some apps are appending `.desktop` to their names in the URL. I had a small if statement in the code but it looks like I was incorrect on that only being present in Loki apps? Do you happen to know the reason why some apps (like Eddy compared to say Alias) have the `.desktop` in their name?

2019-02-14 20:47 UTC, cassidyjames commented
@RMcNeely that's a deprecated thing, but not completely disallowed.

2019-02-26 03:32 UTC, gamerlv commented on lib/app_template.rb
> +		price: <%= @yaml["Custom"] ? @yaml["Custom"]["x-appcenter-suggested-price"] : "0" %>
It is possible to have `Custom` set yet not have `x-appcenter-suggested-price`  Please check for both.

2019-02-26 03:33 UTC, gamerlv commented on lib/app_template.rb
> +		  primary-text: <%= @yaml["Custom"] ? stringify(@yaml['Custom']['x-appcenter-color-primary-text']) : "#fff" %>
It is possible to have `Custom` set yet not have `x-appcenter-color-primary-text`  Please check for both.

2019-02-26 03:43 UTC, gamerlv commented on lib/generate_listings.rb
> +# binding.pry
Is this a left over development comment? If so, could you remove it

2019-02-27 05:46 UTC, RMcNeely commented on lib/app_template.rb
> +		  primary-text: <%= @yaml["Custom"] ? stringify(@yaml['Custom']['x-appcenter-color-primary-text']) : "#fff" %>
I'm falling back to `"#fff"` in the ternary statement if Custom is set but there is no `x-appcenter-primary-text`, or is that not what you mean?

2019-02-27 05:46 UTC, RMcNeely commented on lib/app_template.rb
> +		price: <%= @yaml["Custom"] ? @yaml["Custom"]["x-appcenter-suggested-price"] : "0" %>
same ternary pattern as above except falling back to `"0"`

2019-02-27 05:50 UTC, RMcNeely commented
> Is there a reason to keep the files `_data/appcenter-apps-xenial.yaml` & `_data/appcenter-apps-bionic.yaml` in git version control? It looks like they are regenerated each time the run command is executed.

My thought was that it may be useful to track the files either for debugging or as a useful means to watch the app store grow but you're right, they don't need to be preserved in git. If you think its better to remove them so that they aren't changed so frequently I have no issues removing them.

2019-02-27 11:51 UTC, gamerlv commented on lib/app_template.rb
> +		price: <%= @yaml["Custom"] ? @yaml["Custom"]["x-appcenter-suggested-price"] : "0" %>
If I'm reading the ternary right it's checking if the "Custom" key is set. That is a ruby hash with multiple values; `x-appcenter-color-primary`, `x-appcenter-color-primary-text`, `x-appcenter-suggested-price`.   None of these values are guaranteed to be available. It's possible to set a custom primary text color but not any of the other two.

While testing I saw a few apps that an create empty price value because of this, for example:
- com.github.tkashkin.boiler
- com.github.ryonakano.reco
- com.github.timecraft.notifier

I fixed this same issue a few weeks ago: https://github.com/elementary/appcenter-web/pull/33

2019-02-27 11:55 UTC, gamerlv commented on lib/app_template.rb
> +		  primary-text: <%= @yaml["Custom"] ? stringify(@yaml['Custom']['x-appcenter-color-primary-text']) : "#fff" %>
Here are a few example apps that do have `Custom` but not a text color:
- com.github.panosx2.brightness
- com.github.dahenson.agenda
- com.github.bharatkalluri.gifup
- com.github.writeas.writeas-gtk

2019-02-28 00:51 UTC, RMcNeely commented on lib/app_template.rb
> +		price: <%= @yaml["Custom"] ? @yaml["Custom"]["x-appcenter-suggested-price"] : "0" %>
Thanks for the examples, I'll take a closer look at them.

2019-02-28 03:27 UTC, RMcNeely commented on lib/app_template.rb
> +		price: <%= @yaml["Custom"] ? @yaml["Custom"]["x-appcenter-suggested-price"] : "0" %>
Double checking those three, they are correctly falling back to having a price of 0 since there's no custom price for them in `_data/appcenter-apps-bionic.yaml` The ternary will only take the value for `"x-appcenter-suggested-price"` if it evaluates to be truthy.

2019-02-28 03:36 UTC, RMcNeely commented
Jekyll should be outputting the folders to _site, nothing was specified before so I didn't want to change that. If you think this should be documented I can add more comments @gamerlv

2019-10-02 03:05 UTC, RMcNeely commented
@gamerlv  @cassidyjames what do I need to do to get this merged in? I would like to tackle some more of these issues for Hacktober but I was hoping this could get merged in first

2019-10-02 05:27 UTC, cassidyjames commented
@RMcNeely I can take a more thorough look tomorrow, but I should probably find someone who actually knows Ruby to review it (not me!) :D

2019-10-02 08:31 UTC, gamerlv commented
The only thing blocking this from my perspective is that one open issue on my last review. It reintroduces the bug I linked. One that looks somewhat unprofessional when deployed.

Last time I looked I was able to make that bug happen using this branch but RMcNeely seemly was not. I wasn't sure how to explain that any better. 
I see the current master was merged back in, When I'm back home I'll see if I can still repo it but if you have time before now the issues comes down to the following:

There is a Ruby hash `Custom` with a few elements such as price, color and text-color. These elements may or may not present on a app.
Yet in in the code as is there is only a check if the hash is present, not the elements in the hash. 

This can lead to a situation where if an app had a text-color but no color or price that those fields are still added but just empty, as the ternary condition was met: `Custom` is present.

2019-10-02 12:21 UTC, RMcNeely commented
I see Levi, perhaps the app data had just changed so I was unable to
reproduce but I do understand the concern now. Let me look at this some
more and I'll see about a check.

Sorry if I was being stubborn before.

On Wed, Oct 2, 2019, 4:31 AM Levi Voorintholt <notifications@github.com>
wrote:

> The only thing blocking this from my perspective is that one open issue on
> my last review. It reintroduces the bug I linked. One that looks somewhat
> unprofessional when deployed.
>
> Last time I looked I was able to make that bug happen using this branch
> but RMcNeely seemly was not. I wasn't sure how to explain that any better.
> I see the current master was merged back in, When I'm back home I'll see
> if I can still repo it but if you have time before now the issues comes
> down to the following:
>
> There is a Ruby hash Custom with a few elements such as price, color and
> text-color. These elements may or may not present on a app.
> Yet in in the code as is there is only a check if the hash is present, not
> the elements in the hash.
>
> This can lead to a situation where if an app had a text-color but no color
> or price that those fields are still added but just empty, as the ternary
> condition was met: Custom is present.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elementary/appcenter-web/pull/34?email_source=notifications&email_token=AAVNEHUIPCDSPOYGJPBP3NDQMRL7LA5CNFSM4GXLM572YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAD7PEY#issuecomment-537393043>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAVNEHTK33FFOIIYZKX3FCTQMRL7LANCNFSM4GXLM57Q>
> .
>

2020-10-06 23:05 UTC, cassidyjames requested changes
I think I'm fine with the changes here, but have a few comments/changes.

2020-10-06 23:05 UTC, cassidyjames commented on _apps/com.github.aimproxy.cyfrif.md
> +  primary-text: #fff
These need to be wrapped in quotes, otherwise they're treated as comments

2020-10-06 23:05 UTC, cassidyjames commented on releases.yaml
> +# This file keeps track of the elementary release names and their Ubunt bases
```suggestion
# This file keeps track of the elementary release names and their Ubuntu bases
```

2020-10-06 23:05 UTC, cassidyjames commented on lib/app_template.rb
> +		  primary-text: <%= @yaml["Custom"] && @yaml["Custom"]["x-appcenter-color-primary-text"] ? stringify(@yaml["Custom"]["x-appcenter-color-primary-text"]) : "#fff" %>
I guess this is where the colors would be wrapped in quotes?

2021-08-09 02:55 UTC, RMcNeely commented
Sorry @cassidyjames I missed your review. It looks like you really reworked most of the build process in the main branch, do we need this PR anymore?

2021-08-10 04:05 UTC, cassidyjames commented
@RMcNeely we probably don't this, anymore. I _think_ the ruby files are largely the same as before, though, if this still serves as a reference for future optimization/reworking.

2023-08-16 13:44 UTC, closed without merging

2023-08-16 13:45 UTC, RMcNeely commented
Closing as stale. There's too many changes now for this PR.